[package]
name = "sway-analyzer"
version = "0.1.7"
edition = "2021"
license-file = "LICENSE"
description = "A security-focused static analyzer for Sway written in Rust."
repository = "https://github.com/camden-smallwood/sway-analyzer"
readme = "README.md"

[dependencies]
colored = "2.0.4"
serde = "1.0"
serde_json = "1.0"
structopt = { version = "0.3", default-features = false }
sway-ast = "0.46.1"
sway-error = "0.46.1"
sway-parse = "0.46.1"
sway-types = "0.46.1"
